[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "leomaro7.hello-mcp-server"
version = "0.1.0"
description = "A simple hello MCP server built with FastMCP"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
dependencies = [
    "fastmcp>=3.0.0",
]

[project.scripts]
"leomaro7.hello-mcp-server" = "leomaro7.hello_mcp_server:main"

[tool.hatch.build.targets.wheel]
packages = ["leomaro7"]
